import { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "../../components/ui/dialog";
import { ScrollArea } from "../../components/ui/scroll-area";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "../../components/ui/tabs";
import { Button } from "../../components/ui/button";
import { ExternalLink, FileText, Shield, Wallet } from "lucide-react";

interface TermsAgreementModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export const TermsAgreementModal = ({ open, onOpenChange }: TermsAgreementModalProps) => {
  const [activeTab, setActiveTab] = useState("terms");

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-3xl max-h-[85vh] p-0">
        <DialogHeader className="p-6 pb-0">
          <DialogTitle className="text-xl font-bold">WDC Labs Legal Framework</DialogTitle>
        </DialogHeader>
        
        <Tabs value={activeTab} onValueChange={setActiveTab} className="flex flex-col h-full">
          <TabsList className="mx-6 grid grid-cols-4 gap-1">
            <TabsTrigger value="terms" className="text-xs sm:text-sm">
              <FileText className="w-3 h-3 mr-1 hidden sm:inline" />
              Terms
            </TabsTrigger>
            <TabsTrigger value="privacy" className="text-xs sm:text-sm">
              <Shield className="w-3 h-3 mr-1 hidden sm:inline" />
              Privacy
            </TabsTrigger>
            <TabsTrigger value="data" className="text-xs sm:text-sm">
              <Shield className="w-3 h-3 mr-1 hidden sm:inline" />
              Data
            </TabsTrigger>
            <TabsTrigger value="fintech" className="text-xs sm:text-sm">
              <Wallet className="w-3 h-3 mr-1 hidden sm:inline" />
              Fintech
            </TabsTrigger>
          </TabsList>
          
          <ScrollArea className="flex-1 px-6 py-4" style={{ height: "calc(85vh - 180px)" }}>
            <TabsContent value="terms" className="mt-0 space-y-4 text-sm text-muted-foreground">
              <h3 className="text-lg font-semibold text-foreground">PART 1: TERMS OF USE (THE "RULE BOOK")</h3>
              
              <div className="bg-accent/50 border border-accent p-3 rounded-lg text-accent-foreground">
                <strong>IMPORTANT LEGAL NOTICE:</strong> WDC Labs is a Career Simulation Platform utilizing Artificial Intelligence. By accessing this platform, you acknowledge that "Jobs," "Supervisors" (e.g., Tolu, Emem, Sola), and "Salaries" presented within the simulation are Artificial Intelligence constructs designed for educational purposes, unless explicitly marked as "Live Recruiter" or "Real Job Offer."
              </div>

              <div className="space-y-3">
                <h4 className="font-semibold text-foreground">1. Acceptance of Terms</h4>
                <p>By creating an account, accessing the "Reality Engine," uploading a CV, or utilizing the "Global Wallet," you unconditionally agree to be bound by these Terms. If you do not agree, do not use WDC Labs. These terms constitute a binding legal agreement between you ("User," "Student," "Recruiter") and Wild Fusion Digital Centre.</p>
              </div>

              <div className="space-y-3">
                <h4 className="font-semibold text-foreground">2. The "Reality Engine" & Nature of Services</h4>
                <p><strong>2.1. Simulation vs. Reality:</strong> You understand that the "Virtual Office" is a simulated training environment. Being "fired" by an AI Agent or receiving a "Salary Negotiation" within the simulation does not constitute a legal employment contract or termination under Nigerian Labor Law.</p>
                <p><strong>2.2. AI Interaction:</strong> You consent to interacting with Artificial Intelligence agents. You acknowledge that advice given by Agents (e.g., Coach Kemi) is generated by LLMs and should not be treated as certified financial, legal, medical, or psychological advice.</p>
                <p><strong>2.3. No Guarantee of Employment:</strong> While WDC Labs is designed to prepare you for employment, WDC does not guarantee that you will secure a job, visa, internship, or sponsorship upon completion.</p>
              </div>

              <div className="space-y-3">
                <h4 className="font-semibold text-foreground">3. Account Registration & KYC</h4>
                <p><strong>3.1. Mandatory Verification:</strong> To access "Job-Ready" features or the "Global Wallet," you must complete KYC verification using valid identification (NIN, BVN, International Passport, or Drivers License) as required by the CBN and AML laws.</p>
                <p><strong>3.2. Automated Checks:</strong> You authorize WDC to run background checks via third-party identity verification services.</p>
                <p><strong>3.3. One Account Policy:</strong> Creating multiple accounts to bypass "Ethical Traps," "Firings," or "assessments" is a violation and will result in a permanent ban.</p>
              </div>

              <div className="space-y-3">
                <h4 className="font-semibold text-foreground">4. Payments & NO REFUND POLICY</h4>
                <div className="bg-destructive/10 border border-destructive/20 p-3 rounded-lg text-destructive">
                  <strong>STRICT NO REFUND POLICY:</strong> ALL PAYMENTS ARE FINAL. WDC Labs operates a strict no-refund policy for all subscriptions, bundles, and sponsorship payments.
                </div>
                <p><strong>4.1. Advance Billing:</strong> Subscription fees are billed in advance.</p>
                <p><strong>4.2. Sponsorships:</strong> Funds paid via the "Sponsor an Intern" feature are legally considered gifts and are non-refundable.</p>
              </div>

              <div className="space-y-3">
                <h4 className="font-semibold text-foreground">5. Fintech & Wallet Operations</h4>
                <p><strong>5.1. Not a Bank:</strong> WDC Labs is not a bank. All wallet services are processed by licensed Third-Party Payment Processors.</p>
                <p><strong>5.2. AML/CFT Compliance:</strong> WDC reserves the right to freeze any wallet suspected of being used for money laundering or fraudulent activities.</p>
              </div>

              <div className="space-y-3">
                <h4 className="font-semibold text-foreground">6. Code of Conduct</h4>
                <p><strong>6.1. Academic Integrity:</strong> Using external AI to bypass WDC Labs' AI assessments is strictly prohibited.</p>
                <p><strong>6.2. The Ethical Trap:</strong> The system intentionally tests your integrity. Failing these tests may result in account suspension.</p>
              </div>
            </TabsContent>

            <TabsContent value="privacy" className="mt-0 space-y-4 text-sm text-muted-foreground">
              <h3 className="text-lg font-semibold text-foreground">PART 2: PRIVACY POLICY</h3>
              
              <div className="bg-primary/10 border border-primary/20 p-3 rounded-lg">
                <strong>Commitment:</strong> WDC treats your personal information as private and confidential. We comply fully with the Nigeria Data Protection Act (NDPA) 2023 and GDPR.
              </div>

              <div className="space-y-3">
                <h4 className="font-semibold text-foreground">1. Information We Collect</h4>
                <ul className="list-disc pl-5 space-y-1">
                  <li><strong>Identity Data:</strong> Name, Email, Phone, Address, NIN/BVN (hashed), LinkedIn URL.</li>
                  <li><strong>Biometric Data:</strong> Facial video recordings and Voice recordings processed for educational feedback.</li>
                  <li><strong>Performance Data:</strong> Codes, designs, chat logs with AI agents, and psychometric profiles.</li>
                  <li><strong>Financial Data:</strong> Transaction history, masked card details.</li>
                  <li><strong>Technical Data:</strong> IP address, device type, and cookies.</li>
                </ul>
              </div>

              <div className="space-y-3">
                <h4 className="font-semibold text-foreground">2. Lawful Basis & Usage of Data</h4>
                <p>We process your data based on Contractual Necessity, Legal Obligation, and Legitimate Interest:</p>
                <ul className="list-disc pl-5 space-y-1">
                  <li><strong>AI Training & Analysis:</strong> Sending your content to our AI Orchestrator for grading and feedback.</li>
                  <li><strong>Automated Decision Making:</strong> Using automated systems to grade tasks and determine "Employability."</li>
                  <li><strong>Recruitment Matching:</strong> Sharing your portfolio with Recruiters (if you opt-in).</li>
                </ul>
              </div>

              <div className="space-y-3">
                <h4 className="font-semibold text-foreground">3. The "Data Reaper" Protocol (Retention)</h4>
                <ul className="list-disc pl-5 space-y-1">
                  <li><strong>Biometric Data:</strong> Deleted 7 days after grading.</li>
                  <li><strong>Chat Logs:</strong> Retained for subscription duration + 2 years.</li>
                  <li><strong>Financial Records:</strong> Retained for 5+ years per CBN regulations.</li>
                  <li><strong>Certificates:</strong> Stored permanently.</li>
                </ul>
              </div>

              <div className="space-y-3">
                <h4 className="font-semibold text-foreground">4. International Data Transfers</h4>
                <p>Your data may be transferred to destinations outside Nigeria (EU/US). WDC ensures all transfers are protected by appropriate safeguards including Standard Contractual Clauses.</p>
              </div>

              <div className="space-y-3">
                <h4 className="font-semibold text-foreground">5. Your Rights (NDPA/GDPR)</h4>
                <ul className="list-disc pl-5 space-y-1">
                  <li><strong>Right to be Forgotten:</strong> Request deletion of your account.</li>
                  <li><strong>Right to Rectify:</strong> Update inaccurate information.</li>
                  <li><strong>Right to Withdraw Consent:</strong> Stop AI analysis at any time.</li>
                </ul>
              </div>
            </TabsContent>

            <TabsContent value="data" className="mt-0 space-y-4 text-sm text-muted-foreground">
              <h3 className="text-lg font-semibold text-foreground">PART 3: DATA PROTECTION AGREEMENT</h3>
              
              <p className="italic">Between: Wild Fusion Digital Centre ("Data Controller") and The Partner/Recruiter ("Data Recipient").</p>

              <div className="space-y-3">
                <h4 className="font-semibold text-foreground">1. Scope & Purpose</h4>
                <p>This agreement governs the access to WDC Labs' "Talent Pool," comprising student profiles, portfolios, and AI-generated assessments. The Recipient shall process this data solely for the purpose of evaluating candidates for employment.</p>
              </div>

              <div className="space-y-3">
                <h4 className="font-semibold text-foreground">2. Obligations of the Recipient</h4>
                <p><strong>2.1. Confidentiality:</strong> The Recipient agrees to keep all candidate data strictly confidential.</p>
                <p><strong>2.2. Prohibition on Resale:</strong> The Recipient shall NOT sell, rent, or distribute Student Data to third parties.</p>
                <p><strong>2.3. Data Destruction:</strong> Once a recruitment cycle is closed, the Recipient must delete downloaded CVs within 30 days.</p>
              </div>

              <div className="space-y-3">
                <h4 className="font-semibold text-foreground">3. Liability & Indemnity</h4>
                <p>The Recipient indemnifies WDC against any claims, damages, or fines arising from the Recipient's breach of NDPA/GDPR regarding Student Data.</p>
              </div>
            </TabsContent>

            <TabsContent value="fintech" className="mt-0 space-y-4 text-sm text-muted-foreground">
              <h3 className="text-lg font-semibold text-foreground">PART 4: FINTECH & BANKING ADDENDUM</h3>

              <div className="space-y-3">
                <h4 className="font-semibold text-foreground">1. Regulatory Disclosure</h4>
                <p>Wild Fusion Digital Centre partners with CBN-licensed institutions to facilitate wallet transactions. WDC does not hold depositor funds directly. All funds are held in custodial accounts managed by licensed banking partners.</p>
              </div>

              <div className="space-y-3">
                <h4 className="font-semibold text-foreground">2. Prohibited Transactions</h4>
                <p>You may not use the WDC Wallet for:</p>
                <ul className="list-disc pl-5 space-y-1">
                  <li>Cryptocurrency trading (unless via authorized integration).</li>
                  <li>Gambling, betting, or lottery.</li>
                  <li>Transactions related to illegal drugs, weapons, or adult content.</li>
                  <li>Money laundering or terrorist financing.</li>
                </ul>
              </div>

              <div className="space-y-3">
                <h4 className="font-semibold text-foreground">3. Liability Limitation</h4>
                <p>Access to funds in the "Global Wallet" is subject to the uptime of our banking partners and NIBSS. WDC is not liable for losses caused by third-party bank failures or network downtime.</p>
              </div>

              <div className="mt-6 p-4 bg-muted rounded-lg">
                <h4 className="font-semibold text-foreground mb-2">Contact & Grievance</h4>
                <p>For Privacy concerns, NDPA/GDPR requests, or Legal inquiries:</p>
                <p className="mt-2">
                  <strong>Data Protection Officer (DPO)</strong><br />
                  Email: training@wdc.com.ng<br />
                  Address: 276B Corporation Drive, Dolphin Estate, Ikoyi, Lagos, Nigeria.
                </p>
              </div>
            </TabsContent>
          </ScrollArea>
          
          <div className="p-4 border-t flex justify-end">
            <Button onClick={() => onOpenChange(false)}>Close</Button>
          </div>
        </Tabs>
      </DialogContent>
    </Dialog>
  );
};
