import { NextResponse } from "next/server";

// 🔥 THE COMPLETE LOCAL FALLBACK LIST
const LOCAL_BANK_LIST = [
  {"institutionCode": "000001", "institutionName": "STERLING BANK", "category": 2},
  {"institutionCode": "000002", "institutionName": "KEYSTONE BANK", "category": 2},
  {"institutionCode": "000003", "institutionName": "FCMB", "category": 2},
  {"institutionCode": "000004", "institutionName": "UNITED BANK FOR AFRICA", "category": 2},
  {"institutionCode": "000005", "institutionName": "ACCESS BANK PLC (DIAMOND)", "category": 2},
  {"institutionCode": "000006", "institutionName": "JAIZ BANK", "category": 2},
  {"institutionCode": "000007", "institutionName": "FIDELITY BANK", "category": 2},
  {"institutionCode": "000008", "institutionName": "POLARIS BANK", "category": 2},
  {"institutionCode": "000009", "institutionName": "CITI BANK", "category": 2},
  {"institutionCode": "000010", "institutionName": "ECOBANK BANK", "category": 2},
  {"institutionCode": "000011", "institutionName": "UNITY BANK", "category": 2},
  {"institutionCode": "000012", "institutionName": "STANBICIBTC BANK", "category": 2},
  {"institutionCode": "000013", "institutionName": "GTBANK PLC", "category": 2},
  {"institutionCode": "000014", "institutionName": "ACCESS BANK", "category": 2},
  {"institutionCode": "000015", "institutionName": "ZENITH BANK PLC", "category": 2},
  {"institutionCode": "000016", "institutionName": "FIRST BANK OF NIGERIA", "category": 2},
  {"institutionCode": "000017", "institutionName": "WEMA BANK", "category": 2},
  {"institutionCode": "000018", "institutionName": "UNION BANK", "category": 2},
  {"institutionCode": "000019", "institutionName": "ENTERPRISE BANK", "category": 2},
  {"institutionCode": "000020", "institutionName": "HERITAGE", "category": 2},
  {"institutionCode": "000021", "institutionName": "STANDARDCHARTERED", "category": 2},
  {"institutionCode": "000022", "institutionName": "SUNTRUST BANK", "category": 2},
  {"institutionCode": "000023", "institutionName": "PROVIDUS BANK ", "category": 2},
  {"institutionCode": "000024", "institutionName": "RAND MERCHANT BANK", "category": 6},
  {"institutionCode": "000025", "institutionName": "TITAN TRUST BANK", "category": 2},
  {"institutionCode": "000026", "institutionName": "TAJ BANK", "category": 2},
  {"institutionCode": "000027", "institutionName": "GLOBUS BANK", "category": 2},
  {"institutionCode": "000028", "institutionName": "Central Bank of Nigeria", "category": 2},
  {"institutionCode": "000029", "institutionName": "Lotus Bank", "category": 2},
  {"institutionCode": "000030", "institutionName": "Parallex Bank", "category": 2},
  {"institutionCode": "000031", "institutionName": "Premium Trust bank", "category": 2},
  {"institutionCode": "000033", "institutionName": "e-Naira", "category": 2},
  {"institutionCode": "000034", "institutionName": "Signature Bank", "category": 2},
  {"institutionCode": "000036", "institutionName": "OPTIMUS BANK", "category": 2},
  {"institutionCode": "000037", "institutionName": "Alternative Bank Limited", "category": 2},
  {"institutionCode": "030001", "institutionName": "NEXIM Bank", "category": 3},
  {"institutionCode": "050001", "institutionName": "COUNTY FINANCE LTD", "category": 5},
  {"institutionCode": "050002", "institutionName": "FEWCHORE FINANCE COMPANY LIMITED", "category": 5},
  {"institutionCode": "050003", "institutionName": "SageGrey Finance Limited", "category": 5},
  {"institutionCode": "050004", "institutionName": "NEWEDGE FINANCE LTD", "category": 5},
  {"institutionCode": "050005", "institutionName": "AAA FINANCE", "category": 5},
  {"institutionCode": "050006", "institutionName": "Branch International Financial Services", "category": 5},
  {"institutionCode": "050007", "institutionName": "Tekla Finance Ltd", "category": 5},
  {"institutionCode": "050009", "institutionName": "FAST CREDIT", "category": 5},
  {"institutionCode": "050010", "institutionName": "FUNDQUEST FINANCIAL SERVICES LTD", "category": 5},
  {"institutionCode": "050012", "institutionName": "Enco Finance", "category": 5},
  {"institutionCode": "050013", "institutionName": "Dignity Finance", "category": 5},
  {"institutionCode": "050014", "institutionName": "TRINITY FINANCIAL SERVICES LIMITED", "category": 5},
  {"institutionCode": "050015", "institutionName": "Lukefield Finance Company Limited", "category": 5},
  {"institutionCode": "050016", "institutionName": "E-Finance", "category": 5},
  {"institutionCode": "050017", "institutionName": "CARDINALSTONE FINANCE", "category": 5},
  {"institutionCode": "050020", "institutionName": "Vale Finance Limited", "category": 11},
  {"institutionCode": "060001", "institutionName": "CORONATION", "category": 6},
  {"institutionCode": "060002", "institutionName": "FBNQUEST MERCHANT BANK", "category": 6},
  {"institutionCode": "060003", "institutionName": "NOVA MB", "category": 6},
  {"institutionCode": "060004", "institutionName": "Greenwich Merchant Bank", "category": 6},
  {"institutionCode": "070001", "institutionName": "NPF MICROFINANCE BANK", "category": 9},
  {"institutionCode": "070002", "institutionName": "FORTIS MICROFINANCE BANK", "category": 9},
  {"institutionCode": "070006", "institutionName": "COVENANT MFB", "category": 9},
  {"institutionCode": "070007", "institutionName": "LIVINGTRUST MORTGAGE BANK PLC", "category": 7},
  {"institutionCode": "070008", "institutionName": "PAGE FINANCIALS", "category": 9},
  {"institutionCode": "070009", "institutionName": "GATEWAY MORTGAGE BANK", "category": 7},
  {"institutionCode": "070010", "institutionName": "ABBEY MORTGAGE BANK", "category": 7},
  {"institutionCode": "070011", "institutionName": "REFUGE MORTGAGE BANK", "category": 7},
  {"institutionCode": "070012", "institutionName": "LBIC MORTGAGE BANK", "category": 7},
  {"institutionCode": "070013", "institutionName": "PLATINUM MORTGAGE BANK", "category": 7},
  {"institutionCode": "070014", "institutionName": "FIRST GENERATION MORTGAGE BANK", "category": 7},
  {"institutionCode": "070015", "institutionName": "BRENT MORTGAGE BANK", "category": 7},
  {"institutionCode": "070016", "institutionName": "INFINITY TRUST  MORTGAGE BANK", "category": 7},
  {"institutionCode": "070017", "institutionName": "HAGGAI MORTGAGE BANK", "category": 7},
  {"institutionCode": "070019", "institutionName": "MAYFRESH MORTGAGE BANK", "category": 7},
  {"institutionCode": "070021", "institutionName": "COOP Mortgage Bank", "category": 7},
  {"institutionCode": "070022", "institutionName": "STB Mortgage Bank", "category": 7},
  {"institutionCode": "070023", "institutionName": "Delta Trust Mortgage bank", "category": 7},
  {"institutionCode": "070024", "institutionName": "HomeBase Mortgage", "category": 7},
  {"institutionCode": "070025", "institutionName": "Akwa savings & Loans Limited", "category": 7},
  {"institutionCode": "070026", "institutionName": "FHA MORTGAGE BANK LTD", "category": 7},
  {"institutionCode": "080002", "institutionName": "TajWallet", "category": 10},
  {"institutionCode": "090001", "institutionName": "ASOSAVINGS", "category": 7},
  {"institutionCode": "090003", "institutionName": "JUBILEELIFE", "category": 9},
  {"institutionCode": "090004", "institutionName": "PARRALEX", "category": 9},
  {"institutionCode": "090005", "institutionName": "TRUSTBOND", "category": 7},
  {"institutionCode": "090006", "institutionName": "SAFETRUST", "category": 7},
  {"institutionCode": "090097", "institutionName": "EKONDO MFB", "category": 9},
  {"institutionCode": "090107", "institutionName": "FIRSTTRUST MORGAGES LIMITED", "category": 7},
  {"institutionCode": "090108", "institutionName": "NEW PRUDENTIAL BANK", "category": 7},
  {"institutionCode": "090110", "institutionName": "VFD MFB", "category": 9},
  {"institutionCode": "090111", "institutionName": "FINATRUST MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090112", "institutionName": "SEED CAPITAL MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090113", "institutionName": "MICROVIS MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090114", "institutionName": "EMPIRETRUST MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090115", "institutionName": "TCF", "category": 9},
  {"institutionCode": "090116", "institutionName": "AMML MFB", "category": 9},
  {"institutionCode": "090117", "institutionName": "BOCTRUST MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090118", "institutionName": "IBILE MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090119", "institutionName": "OHAFIA MFB", "category": 9},
  {"institutionCode": "090120", "institutionName": "WETLAND MFB", "category": 9},
  {"institutionCode": "090121", "institutionName": "HASAL MFB", "category": 9},
  {"institutionCode": "090122", "institutionName": "GOWANS MFB", "category": 9},
  {"institutionCode": "090123", "institutionName": "TRUSTBANC J6 MICROFINANCE BANK LIMITED", "category": 9},
  {"institutionCode": "090124", "institutionName": "XSLNCE MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090125", "institutionName": "REGENT MFB", "category": 9},
  {"institutionCode": "090126", "institutionName": "FIDFUND MFB", "category": 9},
  {"institutionCode": "090127", "institutionName": "BC KASH MFB", "category": 9},
  {"institutionCode": "090128", "institutionName": "NDIORAH MFB", "category": 9},
  {"institutionCode": "090129", "institutionName": "MONEYTRUST MFB", "category": 9},
  {"institutionCode": "090130", "institutionName": "CONSUMER  MFB", "category": 9},
  {"institutionCode": "090131", "institutionName": "ALLWORKERS MFB", "category": 9},
  {"institutionCode": "090132", "institutionName": "RICHWAY MFB", "category": 9},
  {"institutionCode": "090133", "institutionName": "AL-BARKAH MFB", "category": 9},
  {"institutionCode": "090134", "institutionName": "ACCION MFB", "category": 9},
  {"institutionCode": "090135", "institutionName": "PERSONAL TRUST MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090136", "institutionName": "MICROCRED MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090137", "institutionName": "PECAN TRUST MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090138", "institutionName": "ROYAL EXCHANGE MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090139", "institutionName": "VISA MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090140", "institutionName": "SAGAMU MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090141", "institutionName": "CHIKUM MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090142", "institutionName": "YES MFB", "category": 9},
  {"institutionCode": "090143", "institutionName": "APEKS MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090144", "institutionName": "CIT MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090145", "institutionName": "FULL RANGE MFB", "category": 9},
  {"institutionCode": "090146", "institutionName": "TRIDENT MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090147", "institutionName": "HACKMAN MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090148", "institutionName": "BOWEN MFB", "category": 9},
  {"institutionCode": "090149", "institutionName": "IRL MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090150", "institutionName": "VIRTUE MFB", "category": 9},
  {"institutionCode": "090151", "institutionName": "MUTUAL TRUST MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090152", "institutionName": "NARGATA MFB", "category": 9},
  {"institutionCode": "090153", "institutionName": "FFS MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090154", "institutionName": "CEMCS MFB", "category": 9},
  {"institutionCode": "090155", "institutionName": "ADVANS LA FAYETTE MFB", "category": 9},
  {"institutionCode": "090156", "institutionName": "E-BARCS MFB", "category": 9},
  {"institutionCode": "090157", "institutionName": "INFINITY MFB", "category": 9},
  {"institutionCode": "090158", "institutionName": "FUTO MFB", "category": 9},
  {"institutionCode": "090159", "institutionName": "CREDIT AFRIQUE MFB", "category": 9},
  {"institutionCode": "090160", "institutionName": "ADDOSSER MFBB", "category": 9},
  {"institutionCode": "090161", "institutionName": "OKPOGA MFB", "category": 9},
  {"institutionCode": "090162", "institutionName": "STANFORD MFB", "category": 9},
  {"institutionCode": "090163", "institutionName": "FIRST MULTIPLE MFB", "category": 9},
  {"institutionCode": "090164", "institutionName": "FIRST ROYAL MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090165", "institutionName": "PETRA MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090166", "institutionName": "ESO-E MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090167", "institutionName": "DAYLIGHT MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090168", "institutionName": "GASHUA MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090169", "institutionName": "ALPHAKAPITAL MFB", "category": 9},
  {"institutionCode": "090170", "institutionName": "RAHAMA MFB", "category": 9},
  {"institutionCode": "090171", "institutionName": "MAINSTREET MFB", "category": 9},
  {"institutionCode": "090172", "institutionName": "ASTRAPOLARIS MFB", "category": 9},
  {"institutionCode": "090173", "institutionName": "RELIANCE MFB", "category": 9},
  {"institutionCode": "090174", "institutionName": "MALACHY MFB", "category": 9},
  {"institutionCode": "090175", "institutionName": "RUBIES MFB", "category": 9},
  {"institutionCode": "090176", "institutionName": "BOSAK MFB", "category": 9},
  {"institutionCode": "090177", "institutionName": "LAPO MFB", "category": 9},
  {"institutionCode": "090178", "institutionName": "GREENBANK MFB", "category": 9},
  {"institutionCode": "090179", "institutionName": "FAST Microfinance Bank", "category": 9},
  {"institutionCode": "090180", "institutionName": "AMJU MFB", "category": 9},
  {"institutionCode": "090181", "institutionName": "Balogun Fulani  Microfinance Bank", "category": 9},
  {"institutionCode": "090182", "institutionName": "Standard MFB", "category": 9},
  {"institutionCode": "090186", "institutionName": "Girei MFB", "category": 9},
  {"institutionCode": "090188", "institutionName": "BAINES CREDIT MFB", "category": 9},
  {"institutionCode": "090189", "institutionName": "ESAN MFB", "category": 9},
  {"institutionCode": "090190", "institutionName": "MUTUAL BENEFITS MFB", "category": 9},
  {"institutionCode": "090191", "institutionName": "KCMB MFB", "category": 9},
  {"institutionCode": "090192", "institutionName": "Midland MFB", "category": 9},
  {"institutionCode": "090193", "institutionName": "UNICAL MFB", "category": 9},
  {"institutionCode": "090194", "institutionName": "NIRSAL NATIONAL MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090195", "institutionName": "GROOMING MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090196", "institutionName": "PENNYWISE MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090197", "institutionName": "ABU MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090198", "institutionName": "RENMONEY MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090201", "institutionName": "XPRESS PAYMENTS", "category": 11},
  {"institutionCode": "090202", "institutionName": "ACCELEREX NETWORK", "category": 11},
  {"institutionCode": "090205", "institutionName": "NEWDAWN MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090211", "institutionName": "ITEX INTEGRATED SERVICES LIMITED", "category": 11},
  {"institutionCode": "090251", "institutionName": "UNN MFB", "category": 9},
  {"institutionCode": "090252", "institutionName": "Yobe MFB", "category": 9},
  {"institutionCode": "090253", "institutionName": "Wudil Microfinance Bank", "category": 9},
  {"institutionCode": "090254", "institutionName": "CoalCamp Microfinance Bank", "category": 9},
  {"institutionCode": "090258", "institutionName": "IMO MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090259", "institutionName": "ALEKUN MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090260", "institutionName": "ABOVE ONLY MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090261", "institutionName": "QUICKFUND MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090262", "institutionName": "STELLAS MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090263", "institutionName": "NAVY MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090264", "institutionName": "AUCHI MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090265", "institutionName": "LOVONUS MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090266", "institutionName": "UNIBEN MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090267", "institutionName": "KUDA MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090268", "institutionName": "ADEYEMI COLLEGE STAFF MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090269", "institutionName": "GREENVILLE MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090270", "institutionName": "AB MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090271", "institutionName": "LAVENDER MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090272", "institutionName": "OLABISI ONABANJO UNIVERSITY MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090273", "institutionName": "EMERALDS MFB", "category": 9},
  {"institutionCode": "090274", "institutionName": "PRESTIGE MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090275", "institutionName": "MERIDIAN MFB", "category": 9},
  {"institutionCode": "090276", "institutionName": "TRUSTFUND MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090277", "institutionName": "ALHAYAT MFB", "category": 9},
  {"institutionCode": "090278", "institutionName": "GLORY MFB ", "category": 9},
  {"institutionCode": "090279", "institutionName": "IKIRE MFB", "category": 9},
  {"institutionCode": "090280", "institutionName": "MEGAPRAISE MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090281", "institutionName": "FINEX MFB", "category": 9},
  {"institutionCode": "090282", "institutionName": "ARISE MFB", "category": 9},
  {"institutionCode": "090283", "institutionName": "THRIVE MFB", "category": 9},
  {"institutionCode": "090285", "institutionName": "FIRST OPTION MFB", "category": 9},
  {"institutionCode": "090286", "institutionName": "SafeHaven Microfinance Bank", "category": 9},
  {"institutionCode": "090287", "institutionName": "Assets Matrix MFB", "category": 9},
  {"institutionCode": "090289", "institutionName": "PILLAR MFB", "category": 9},
  {"institutionCode": "090290", "institutionName": "FCT MFB", "category": 9},
  {"institutionCode": "090291", "institutionName": "HalaCredit MFB", "category": 9},
  {"institutionCode": "090292", "institutionName": "Afekhafe MFB", "category": 9},
  {"institutionCode": "090293", "institutionName": "BRETHREN MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090294", "institutionName": "EAGLE FLIGHT MFB", "category": 9},
  {"institutionCode": "090295", "institutionName": "OMIYE MFB", "category": 9},
  {"institutionCode": "090296", "institutionName": "POLYUWANNA MFB", "category": 9},
  {"institutionCode": "090297", "institutionName": "ALERT MFB", "category": 9},
  {"institutionCode": "090298", "institutionName": "FEDERALPOLY NASARAWAMFB", "category": 9},
  {"institutionCode": "090299", "institutionName": "KONTAGORA MFB", "category": 9},
  {"institutionCode": "090302", "institutionName": "Sunbeam Microfinance Bank", "category": 9},
  {"institutionCode": "090303", "institutionName": "PURPLEMONEY MFB", "category": 9},
  {"institutionCode": "090304", "institutionName": "EVANGEL MFB", "category": 9},
  {"institutionCode": "090305", "institutionName": "SULSAP MFB", "category": 9},
  {"institutionCode": "090307", "institutionName": "Aramoko Microfinance Bank", "category": 9},
  {"institutionCode": "090308", "institutionName": "BRIGHTWAY MFB", "category": 9},
  {"institutionCode": "090310", "institutionName": "EDFIN MFB", "category": 9},
  {"institutionCode": "090315", "institutionName": "U and C Microfinance Bank Limited", "category": 9},
  {"institutionCode": "090316", "institutionName": "BAYERO MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090317", "institutionName": "PATRICK GOLD", "category": 9},
  {"institutionCode": "090318", "institutionName": "FEDERAL UNIVERSITY DUTSE  MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090319", "institutionName": "Bonghe Microfinance Bank", "category": 9},
  {"institutionCode": "090320", "institutionName": "KADPOLY MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090321", "institutionName": "MAYFAIR  MFB", "category": 9},
  {"institutionCode": "090322", "institutionName": "REPHIDIM MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090323", "institutionName": "MAINLAND MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090324", "institutionName": "IKENNE MFB", "category": 9},
  {"institutionCode": "090325", "institutionName": "SPARKLE MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090326", "institutionName": "BALOGUN GAMBARI MFB", "category": 9},
  {"institutionCode": "090327", "institutionName": "TRUST MFB", "category": 9},
  {"institutionCode": "090328", "institutionName": "EYOWO MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090329", "institutionName": "NEPTUNE MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090330", "institutionName": "FAME Microfinance Bank", "category": 9},
  {"institutionCode": "090331", "institutionName": "UNAAB MFB", "category": 9},
  {"institutionCode": "090332", "institutionName": "EVERGREEN MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090333", "institutionName": "OCHE MFB", "category": 9},
  {"institutionCode": "090335", "institutionName": "Grant Microfinance Bank", "category": 9},
  {"institutionCode": "090336", "institutionName": "BIPC MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090337", "institutionName": "IYERU OKIN MICROFINANCE BANK LTD", "category": 9},
  {"institutionCode": "090338", "institutionName": "UniUyo Microfinance Bank", "category": 9},
  {"institutionCode": "090340", "institutionName": "Stockcorp  Microfinance Bank", "category": 9},
  {"institutionCode": "090341", "institutionName": "unilorin Microfinance Bank", "category": 9},
  {"institutionCode": "090343", "institutionName": "Citizen Trust Microfinance Bank Ltd", "category": 9},
  {"institutionCode": "090345", "institutionName": "OAU MICROFINANCE BANK LTD", "category": 9},
  {"institutionCode": "090349", "institutionName": "Nasarawa Microfinance bank", "category": 9},
  {"institutionCode": "090350", "institutionName": "Illorin Microfinance Bank", "category": 9},
  {"institutionCode": "090352", "institutionName": "Jessefield Microfinance Bank", "category": 9},
  {"institutionCode": "090353", "institutionName": "Isuofia MFB", "category": 9},
  {"institutionCode": "090360", "institutionName": "CASHCONNECT   MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090362", "institutionName": "MOLUSI MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090363", "institutionName": "Headway MFB", "category": 9},
  {"institutionCode": "090364", "institutionName": "NUTURE MFB", "category": 9},
  {"institutionCode": "090365", "institutionName": "Corestep MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090366", "institutionName": "Firmus MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090369", "institutionName": "SEEDVEST MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090370", "institutionName": "ILASAN MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090371", "institutionName": "AGOSASA MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090372", "institutionName": "LEGEND MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090373", "institutionName": "TF MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090374", "institutionName": "COASTLINE MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090376", "institutionName": "APPLE  MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090377", "institutionName": "ISALEOYO MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090378", "institutionName": "NEW GOLDEN PASTURES MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090379", "institutionName": "PENIEL MICORFINANCE BANK LTD", "category": 9},
  {"institutionCode": "090380", "institutionName": "KREDI MONEY MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090383", "institutionName": "MANNY MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090384", "institutionName": "ZION MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090385", "institutionName": "GTI  Microfinance Bank", "category": 9},
  {"institutionCode": "090386", "institutionName": "Interland MFB", "category": 9},
  {"institutionCode": "090389", "institutionName": "EK-Reliable Microfinance Bank", "category": 9},
  {"institutionCode": "090390", "institutionName": "Parkway MF Bank", "category": 9},
  {"institutionCode": "090391", "institutionName": "Davodani  Microfinance Bank", "category": 9},
  {"institutionCode": "090392", "institutionName": "Mozfin Microfinance Bank", "category": 9},
  {"institutionCode": "090393", "institutionName": "Bridgeway Microfinance Bank", "category": 9},
  {"institutionCode": "090394", "institutionName": "Amac Microfinance Bank", "category": 9},
  {"institutionCode": "090395", "institutionName": "Borgu MFB", "category": 9},
  {"institutionCode": "090396", "institutionName": "Oscotech MFB", "category": 9},
  {"institutionCode": "090397", "institutionName": "Chanelle Bank", "category": 9},
  {"institutionCode": "090398", "institutionName": "Federal Polytechnic Nekede Microfinance Bank", "category": 9},
  {"institutionCode": "090399", "institutionName": "Nwannegadi MFB", "category": 9},
  {"institutionCode": "090400", "institutionName": "Finca Microfinance Bank", "category": 9},
  {"institutionCode": "090401", "institutionName": "Shepherd Trust Microfinance Bank", "category": 9},
  {"institutionCode": "090402", "institutionName": "Peace Microfinance Bank", "category": 9},
  {"institutionCode": "090403", "institutionName": "UDA Microfinance Bank", "category": 9},
  {"institutionCode": "090404", "institutionName": "Olowolagba Microfinance Bank", "category": 9},
  {"institutionCode": "090405", "institutionName": "MONIEPOINT MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090406", "institutionName": "Business Support Microfinance Bank", "category": 9},
  {"institutionCode": "090409", "institutionName": "FCMB MFB", "category": 9},
  {"institutionCode": "090410", "institutionName": "Maritime Microfinance Bank", "category": 9},
  {"institutionCode": "090411", "institutionName": "GiGinya Microfinance Bank", "category": 9},
  {"institutionCode": "090412", "institutionName": "Preeminent Microfinance Bank", "category": 9},
  {"institutionCode": "090413", "institutionName": "Benysta Microfinance Bank", "category": 9},
  {"institutionCode": "090414", "institutionName": "Crutech  Microfinance Bank", "category": 9},
  {"institutionCode": "090415", "institutionName": "Calabar Microfinance Bank", "category": 9},
  {"institutionCode": "090416", "institutionName": "Chibueze Microfinance Bank", "category": 9},
  {"institutionCode": "090417", "institutionName": "Imowo Microfinance Bank", "category": 9},
  {"institutionCode": "090418", "institutionName": "Highland Microfinance Bank", "category": 9},
  {"institutionCode": "090419", "institutionName": "WinView Bank", "category": 9},
  {"institutionCode": "090420", "institutionName": "LETSHEGO MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090421", "institutionName": "Izon Microfinance Bank", "category": 9},
  {"institutionCode": "090422", "institutionName": "Landgold  Microfinance Bank", "category": 9},
  {"institutionCode": "090423", "institutionName": "Mautech  Microfinance Bank", "category": 9},
  {"institutionCode": "090424", "institutionName": "Abucoop  Microfinance Bank", "category": 9},
  {"institutionCode": "090425", "institutionName": "Banex Microfinance Bank", "category": 9},
  {"institutionCode": "090426", "institutionName": "Tangerine Money MFB", "category": 9},
  {"institutionCode": "090427", "institutionName": "EBSU MICROFINANCE Bank", "category": 9},
  {"institutionCode": "090428", "institutionName": "Ishie  Microfinance Bank", "category": 9},
  {"institutionCode": "090429", "institutionName": "CrossRiver  Microfinance Bank", "category": 9},
  {"institutionCode": "090430", "institutionName": "Ilora Microfinance Bank", "category": 9},
  {"institutionCode": "090431", "institutionName": "Bluewhales  Microfinance Bank", "category": 9},
  {"institutionCode": "090432", "institutionName": "Memphis Microfinance Bank", "category": 9},
  {"institutionCode": "090433", "institutionName": "RIGO Microfinance Bank", "category": 9},
  {"institutionCode": "090434", "institutionName": "Insight Microfinance Bank", "category": 9},
  {"institutionCode": "090435", "institutionName": "Links  Microfinance Bank", "category": 9},
  {"institutionCode": "090436", "institutionName": "Spectrum Microfinance Bank", "category": 9},
  {"institutionCode": "090437", "institutionName": "Oakland Microfinance Bank", "category": 9},
  {"institutionCode": "090438", "institutionName": "Futminna Microfinance Bank", "category": 9},
  {"institutionCode": "090439", "institutionName": "IBETO  Microfinance Bank", "category": 9},
  {"institutionCode": "090440", "institutionName": "Cherish Microfinance Bank", "category": 9},
  {"institutionCode": "090441", "institutionName": "Giwa Microfinance Bank", "category": 9},
  {"institutionCode": "090443", "institutionName": "RIMA Microfinance Bank", "category": 9},
  {"institutionCode": "090444", "institutionName": "BOI MF Bank", "category": 9},
  {"institutionCode": "090445", "institutionName": "Capstone MF Bank", "category": 9},
  {"institutionCode": "090446", "institutionName": "Support MF Bank", "category": 9},
  {"institutionCode": "090448", "institutionName": "Moyofade MF Bank", "category": 9},
  {"institutionCode": "090449", "institutionName": "REX Microfinance Bank", "category": 9},
  {"institutionCode": "090450", "institutionName": "Kwasu MF Bank", "category": 9},
  {"institutionCode": "090451", "institutionName": "ATBU  Microfinance Bank", "category": 9},
  {"institutionCode": "090452", "institutionName": "Unilag  Microfinance Bank", "category": 9},
  {"institutionCode": "090453", "institutionName": "Uzondu MF Bank", "category": 9},
  {"institutionCode": "090454", "institutionName": "Borstal Microfinance Bank", "category": 9},
  {"institutionCode": "090455", "institutionName": "MKOBO MICROFINANCE BANK LTD", "category": 9},
  {"institutionCode": "090456", "institutionName": "Ospoly Microfinance Bank", "category": 9},
  {"institutionCode": "090459", "institutionName": "Nice Microfinance Bank", "category": 9},
  {"institutionCode": "090460", "institutionName": "OLUYOLE MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090461", "institutionName": "UNIIBADAN Microfinance Bank", "category": 9},
  {"institutionCode": "090462", "institutionName": "Monarch Microfinance Bank", "category": 9},
  {"institutionCode": "090463", "institutionName": "Rehoboth Microfinance Bank", "category": 9},
  {"institutionCode": "090464", "institutionName": "Unimaid Microfinance Bank", "category": 9},
  {"institutionCode": "090465", "institutionName": "Maintrust MFB", "category": 9},
  {"institutionCode": "090466", "institutionName": "YCT Microfinance Bank", "category": 9},
  {"institutionCode": "090467", "institutionName": "Good Neighbours Microfinance Bank", "category": 9},
  {"institutionCode": "090468", "institutionName": "OLOFIN OWENA Microfinance Bank", "category": 9},
  {"institutionCode": "090469", "institutionName": "Aniocha MFB", "category": 9},
  {"institutionCode": "090470", "institutionName": "DOT MFB", "category": 9},
  {"institutionCode": "090471", "institutionName": "OLUCHUKWU Microfinance Bank", "category": 9},
  {"institutionCode": "090472", "institutionName": "CARETAKER Microfinance Bank", "category": 9},
  {"institutionCode": "090473", "institutionName": "ASSETS Microfinance Bank", "category": 9},
  {"institutionCode": "090474", "institutionName": "Verdant Microfinance Bank", "category": 9},
  {"institutionCode": "090475", "institutionName": "Giant Stride MFB", "category": 9},
  {"institutionCode": "090476", "institutionName": "Anchorage MFB", "category": 9},
  {"institutionCode": "090477", "institutionName": "Light Microfinance Bank", "category": 9},
  {"institutionCode": "090478", "institutionName": "Avuenegbe MFB", "category": 9},
  {"institutionCode": "090479", "institutionName": "First Heritage MFB", "category": 9},
  {"institutionCode": "090480", "institutionName": "Kolomoni Microfinance Bank Ltd", "category": 9},
  {"institutionCode": "090481", "institutionName": "Prisco  Microfinance Bank", "category": 9},
  {"institutionCode": "090482", "institutionName": "Fedeth MFB", "category": 9},
  {"institutionCode": "090483", "institutionName": "Ada MFB", "category": 9},
  {"institutionCode": "090484", "institutionName": "Garki MFB", "category": 9},
  {"institutionCode": "090485", "institutionName": "Safegate Microfinance Bank", "category": 9},
  {"institutionCode": "090486", "institutionName": "Fortress Microfinance Bank", "category": 9},
  {"institutionCode": "090487", "institutionName": "Kingdom College  Microfinance Bank", "category": 9},
  {"institutionCode": "090488", "institutionName": "Ibu-Aje Microfinance", "category": 9},
  {"institutionCode": "090489", "institutionName": "Alvana Microfinance Bank", "category": 9},
  {"institutionCode": "090490", "institutionName": "Chukwunenye  Microfinance Bank", "category": 9},
  {"institutionCode": "090491", "institutionName": "Nsuk  Microfinance Bank", "category": 9},
  {"institutionCode": "090492", "institutionName": "Oraukwu  Microfinance Bank", "category": 9},
  {"institutionCode": "090493", "institutionName": "Iperu Microfinance Bank", "category": 9},
  {"institutionCode": "090494", "institutionName": "Boji Boji Microfinance Bank", "category": 9},
  {"institutionCode": "090495", "institutionName": "Goodnews Microfinance Bank", "category": 9},
  {"institutionCode": "090496", "institutionName": "Radalpha Microfinance bank", "category": 9},
  {"institutionCode": "090497", "institutionName": "Palmcoast Microfinance bank", "category": 9},
  {"institutionCode": "090498", "institutionName": "Catland Microfinance Bank", "category": 9},
  {"institutionCode": "090499", "institutionName": "Pristine Divitis Microfinance Bank", "category": 9},
  {"institutionCode": "090500", "institutionName": "Gwong Microfinance bank", "category": 9},
  {"institutionCode": "090501", "institutionName": "Boromu Microfinance bank", "category": 9},
  {"institutionCode": "090502", "institutionName": "Shalom Microfinance Bank", "category": 9},
  {"institutionCode": "090503", "institutionName": "Projects Microfinance bank", "category": 9},
  {"institutionCode": "090504", "institutionName": "Zikora Microfinance bank", "category": 9},
  {"institutionCode": "090505", "institutionName": "Nigeria PrisonsMicrofinance bank", "category": 9},
  {"institutionCode": "090506", "institutionName": "Solid Allianze MFB", "category": 9},
  {"institutionCode": "090507", "institutionName": "FIMS MFB", "category": 9},
  {"institutionCode": "090508", "institutionName": "Borno Renaissance Microfinance bank", "category": 9},
  {"institutionCode": "090509", "institutionName": "CAPITALMETRIQ SWIFT MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090510", "institutionName": "Umunnachi Microfinance Bank", "category": 9},
  {"institutionCode": "090511", "institutionName": "Cloverleaf  MFB", "category": 9},
  {"institutionCode": "090512", "institutionName": "BUBAYERO Microfinance Bank", "category": 9},
  {"institutionCode": "090513", "institutionName": "SEAP Microfinance Bank", "category": 9},
  {"institutionCode": "090514", "institutionName": "Umuchinemere Procredit Microfinance Bank", "category": 9},
  {"institutionCode": "090515", "institutionName": "Rima Growth pathway Microfinance Bank ", "category": 9},
  {"institutionCode": "090516", "institutionName": "Numo Microfinance bank", "category": 9},
  {"institutionCode": "090517", "institutionName": "Uhuru Microfinance bank", "category": 9},
  {"institutionCode": "090518", "institutionName": "Afemai Microfinance Bank", "category": 9},
  {"institutionCode": "090519", "institutionName": "Ibom fadama Microfinance Bank", "category": 9},
  {"institutionCode": "090520", "institutionName": "IC GLOBALMicrofinance bank", "category": 9},
  {"institutionCode": "090521", "institutionName": "Foresight Microfinance bank", "category": 9},
  {"institutionCode": "090523", "institutionName": "Chase Microfinance bank", "category": 9},
  {"institutionCode": "090524", "institutionName": "Solidrock Microfinance bank", "category": 9},
  {"institutionCode": "090525", "institutionName": "Triple A Microfinance bank", "category": 9},
  {"institutionCode": "090526", "institutionName": "Crescent Microfinance bank", "category": 9},
  {"institutionCode": "090527", "institutionName": "Ojokoro Mfb", "category": 9},
  {"institutionCode": "090528", "institutionName": "Mgbidi Microfinance Bank", "category": 9},
  {"institutionCode": "090529", "institutionName": "Bankly Microfinance bank", "category": 9},
  {"institutionCode": "090530", "institutionName": "CONFIDENCE MICROFINANCE BANK LTD", "category": 9},
  {"institutionCode": "090531", "institutionName": "Aku MFB", "category": 9},
  {"institutionCode": "090532", "institutionName": "IBOLO MICORFINANCE BANK LTD", "category": 9},
  {"institutionCode": "090534", "institutionName": "Polyibadan Microfinance Bank", "category": 9},
  {"institutionCode": "090535", "institutionName": "NKPOLU-UST MICROFINANCE", "category": 9},
  {"institutionCode": "090536", "institutionName": "Ikoyi-Osun Microfinance Bank", "category": 9},
  {"institutionCode": "090537", "institutionName": "Lobrem Microfinance Bank", "category": 9},
  {"institutionCode": "090538", "institutionName": "Blue Investments Microfinance Bank", "category": 9},
  {"institutionCode": "090539", "institutionName": "Enrich Microfinance Bank", "category": 9},
  {"institutionCode": "090540", "institutionName": "Aztec Microfinance Bank", "category": 9},
  {"institutionCode": "090541", "institutionName": "EXCELLENT MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090542", "institutionName": "OTUO MICROFINANCE BANK LTD", "category": 9},
  {"institutionCode": "090543", "institutionName": "IWOAMA MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090544", "institutionName": "ASPIRE MICROFINANCE BANK LTD", "category": 9},
  {"institutionCode": "090545", "institutionName": "ABULESORO MICROFINANCE BANK LTD", "category": 9},
  {"institutionCode": "090546", "institutionName": "IJEBU-IFE MICROFINANCE BANK LTD", "category": 9},
  {"institutionCode": "090547", "institutionName": "ROCKSHIELD MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090548", "institutionName": "ALLY MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090549", "institutionName": "KC MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090550", "institutionName": "GREEN ENERGY MICROFINANCE BANK LTD", "category": 9},
  {"institutionCode": "090551", "institutionName": "FAIRMONEY MICROFINANCE BANK LTD", "category": 9},
  {"institutionCode": "090552", "institutionName": "EKIMOGUN MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090553", "institutionName": "CONSISTENT TRUST MICROFINANCE BANK LTD", "category": 9},
  {"institutionCode": "090554", "institutionName": "KAYVEE MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090555", "institutionName": "BISHOPGATE MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090556", "institutionName": "EGWAFIN MICROFINANCE BANK LTD", "category": 9},
  {"institutionCode": "090557", "institutionName": "LIFEGATE MICROFINANCE BANK LTD", "category": 9},
  {"institutionCode": "090558", "institutionName": "SHONGOM MICROFINANCE BANK LTD", "category": 9},
  {"institutionCode": "090559", "institutionName": "SHIELD MICROFINANCE BANK LTD", "category": 9},
  {"institutionCode": "090560", "institutionName": "TANADI MICROFINANCE BANK LTD", "category": 9},
  {"institutionCode": "090561", "institutionName": "AKUCHUKWU MICROFINANCE BANK LTD", "category": 9},
  {"institutionCode": "090562", "institutionName": "CEDAR MICROFINANCE BANK LTD", "category": 9},
  {"institutionCode": "090563", "institutionName": "BALERA MICROFINANCE BANK LTD", "category": 9},
  {"institutionCode": "090564", "institutionName": "SUPREME MICROFINANCE BANK LTD", "category": 9},
  {"institutionCode": "090565", "institutionName": "OKE-ARO OREDEGBE MICROFINANCE BANK LTD", "category": 9},
  {"institutionCode": "090566", "institutionName": "OKUKU MICROFINANCE BANK LTD", "category": 9},
  {"institutionCode": "090567", "institutionName": "OROKAM MICROFINANCE BANK LTD", "category": 9},
  {"institutionCode": "090568", "institutionName": "BROADVIEW MICROFINANCE BANK LTD", "category": 9},
  {"institutionCode": "090569", "institutionName": "QUBE MICROFINANCE BANK LTD", "category": 9},
  {"institutionCode": "090570", "institutionName": "IYAMOYE MICROFINANCE BANK LTD", "category": 9},
  {"institutionCode": "090571", "institutionName": "ILARO POLY MICROFINANCE BANK LTD", "category": 9},
  {"institutionCode": "090572", "institutionName": "EWT Microfinance Bank", "category": 9},
  {"institutionCode": "090573", "institutionName": "SNOW MFB", "category": 9},
  {"institutionCode": "090574", "institutionName": "GOLDMAN MICROFINANCE BANK LTD", "category": 9},
  {"institutionCode": "090575", "institutionName": "FIRSTMIDAS MICROFINANCE BANK LTD", "category": 9},
  {"institutionCode": "090576", "institutionName": "OCTOPUS MICROFINANCE BANK LTD", "category": 9},
  {"institutionCode": "090578", "institutionName": "IWADE MICROFINANCE BANK LTD", "category": 9},
  {"institutionCode": "090579", "institutionName": "GBEDE Microfinance Bank", "category": 9},
  {"institutionCode": "090580", "institutionName": "OTECH MICROFINANCE BANK LTD", "category": 9},
  {"institutionCode": "090581", "institutionName": "BANC CORP MICROFINANCE BANK LTD", "category": 9},
  {"institutionCode": "090582", "institutionName": "Gabasawa MFB", "category": 9},
  {"institutionCode": "090583", "institutionName": "STATESIDE MFB", "category": 9},
  {"institutionCode": "090584", "institutionName": "ISLAND MICROFINANCE BANK LTD", "category": 9},
  {"institutionCode": "090586", "institutionName": "GOMBE MICROFINANCE BANK LTD", "category": 9},
  {"institutionCode": "090587", "institutionName": "Microbiz MFB", "category": 9},
  {"institutionCode": "090588", "institutionName": "Orisun MFB", "category": 9},
  {"institutionCode": "090589", "institutionName": "MERCURY MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090590", "institutionName": "WAYA MICROFINANCE BANK LTD", "category": 9},
  {"institutionCode": "090591", "institutionName": "Gabsyn MFB", "category": 9},
  {"institutionCode": "090592", "institutionName": "Kano Poly MFB", "category": 9},
  {"institutionCode": "090593", "institutionName": "TASUED MICROFINANCE BANK LTD", "category": 9},
  {"institutionCode": "090596", "institutionName": "DAL Microfinance Bank", "category": 9},
  {"institutionCode": "090597", "institutionName": "KABO MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090598", "institutionName": "IBA MFB", "category": 9},
  {"institutionCode": "090599", "institutionName": "Greenacres MFB", "category": 9},
  {"institutionCode": "090600", "institutionName": "AVE MARIA MICROFINANCE BANK LTD", "category": 9},
  {"institutionCode": "090602", "institutionName": "KENECHUKWU MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090603", "institutionName": "Macrod MFB", "category": 9},
  {"institutionCode": "090605", "institutionName": "MADOBI MFB", "category": 9},
  {"institutionCode": "090606", "institutionName": "KKU Microfinance Bank", "category": 9},
  {"institutionCode": "090607", "institutionName": "MINJIBIR MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090608", "institutionName": "Akpo Microfinance Bank", "category": 9},
  {"institutionCode": "090609", "institutionName": "Ummah Microfinance Bank", "category": 9},
  {"institutionCode": "090610", "institutionName": "AMOYE MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090611", "institutionName": "Creditville MFB", "category": 9},
  {"institutionCode": "090612", "institutionName": "Medef MFB", "category": 9},
  {"institutionCode": "090613", "institutionName": "Total Trust Microfinance Bank", "category": 9},
  {"institutionCode": "090614", "institutionName": "Flourish MFB", "category": 9},
  {"institutionCode": "090615", "institutionName": "Beststar MFB", "category": 9},
  {"institutionCode": "090616", "institutionName": "RAYYAN MFB", "category": 9},
  {"institutionCode": "090618", "institutionName": "BERACHAH MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090620", "institutionName": "Iyin Ekiti MFB", "category": 9},
  {"institutionCode": "090621", "institutionName": "GIDAUNIYAR ALHERI MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090622", "institutionName": "Royal Blue MFB", "category": 9},
  {"institutionCode": "090623", "institutionName": "Mab Allianz MFB", "category": 9},
  {"institutionCode": "090625", "institutionName": "Babura Microfinance Bank", "category": 9},
  {"institutionCode": "090626", "institutionName": "OHHA Microfinance Bank", "category": 9},
  {"institutionCode": "090628", "institutionName": "Nsehe Microfinance Bank", "category": 9},
  {"institutionCode": "090630", "institutionName": "Mabinas MFB", "category": 9},
  {"institutionCode": "090633", "institutionName": "Awacash Microfinance Bank", "category": 9},
  {"institutionCode": "090634", "institutionName": "CASHBRIDGE MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090635", "institutionName": "Oyan Microfinance Bank", "category": 9},
  {"institutionCode": "090636", "institutionName": "Briyth Covenant Microfinance Bank", "category": 9},
  {"institutionCode": "090637", "institutionName": "Unifund Microfinance Bank", "category": 9},
  {"institutionCode": "090638", "institutionName": "Tangale Microfinance Bank", "category": 9},
  {"institutionCode": "090639", "institutionName": "GLOBAL INITIATIVE MFB", "category": 9},
  {"institutionCode": "090640", "institutionName": "ABSU Microfinance Bank", "category": 9},
  {"institutionCode": "090641", "institutionName": "SOURCE MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090642", "institutionName": "Prosperity Microfinance Bank", "category": 9},
  {"institutionCode": "090643", "institutionName": "DIOBU MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090644", "institutionName": "SUNTOP MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090645", "institutionName": "Amucha Microfinance Bank", "category": 9},
  {"institutionCode": "090646", "institutionName": "Okengwe MFB", "category": 9},
  {"institutionCode": "090647", "institutionName": "Canaan Microfinance Bank", "category": 9},
  {"institutionCode": "090649", "institutionName": "Cashrite MFB", "category": 9},
  {"institutionCode": "090650", "institutionName": "Leadcity MFB", "category": 9},
  {"institutionCode": "090651", "institutionName": "BAM MFB", "category": 9},
  {"institutionCode": "090652", "institutionName": "UMUCHUKWU MICROFINANCE BANK", "category": 9},
  {"institutionCode": "090654", "institutionName": "Odoakpu MFB", "category": 9},
  {"institutionCode": "090655", "institutionName": "Bunkure MFB", "category": 9},
  {"institutionCode": "090656", "institutionName": "Entity MFB ", "category": 9},
  {"institutionCode": "090657", "institutionName": "Pyramid MFB", "category": 9},
  {"institutionCode": "090659", "institutionName": "MOUA MFB", "category": 9},
  {"institutionCode": "090661", "institutionName": "Bundi MFB", "category": 9},
  {"institutionCode": "090662", "institutionName": "Awesome MFB", "category": 9},
  {"institutionCode": "090663", "institutionName": "Treasures MFB", "category": 9},
  {"institutionCode": "090664", "institutionName": "Good Shephard MFB ", "category": 9},
  {"institutionCode": "090666", "institutionName": "REVELATION MICRO FINANCE BANK LIMITED", "category": 9},
  {"institutionCode": "100001", "institutionName": "FETS", "category": 10},
  {"institutionCode": "100002", "institutionName": "PAGA", "category": 10},
  {"institutionCode": "100003", "institutionName": "PARKWAY-READYCASH", "category": 10},
  {"institutionCode": "100004", "institutionName": "OPAY", "category": 10},
  {"institutionCode": "100005", "institutionName": "CELLULANT", "category": 10},
  {"institutionCode": "100006", "institutionName": "ETRANZACT", "category": 10},
  {"institutionCode": "100007", "institutionName": "STANBIC IBTC @EASE WALLET", "category": 10},
  {"institutionCode": "100008", "institutionName": "ECOBANK XPRESS ACCOUNT", "category": 10},
  {"institutionCode": "100009", "institutionName": "GTMOBILE", "category": 10},
  {"institutionCode": "100010", "institutionName": "TEASYMOBILE", "category": 10},
  {"institutionCode": "100011", "institutionName": "MKUDI", "category": 10},
  {"institutionCode": "100012", "institutionName": "VTNetwork", "category": 11},
  {"institutionCode": "100013", "institutionName": "ACCESSMONEY", "category": 10},
  {"institutionCode": "100014", "institutionName": "FIRSTMONIE WALLET", "category": 10},
  {"institutionCode": "100016", "institutionName": "FORTISMOBILE", "category": 10},
  {"institutionCode": "100017", "institutionName": "HEDONMARK", "category": 10},
  {"institutionCode": "100018", "institutionName": "ZENITHMOBILE", "category": 10},
  {"institutionCode": "100019", "institutionName": "FIDELITY MOBILE", "category": 10},
  {"institutionCode": "100020", "institutionName": "MONEYBOX", "category": 10},
  {"institutionCode": "100022", "institutionName": "GOMONEY", "category": 10},
  {"institutionCode": "100023", "institutionName": "TAGPAY", "category": 10},
  {"institutionCode": "100024", "institutionName": "IMPERIAL HOMES MORTGAGE BANK", "category": 7},
  {"institutionCode": "100025", "institutionName": "KONGAPAY", "category": 10},
  {"institutionCode": "100026", "institutionName": "CARBON", "category": 9},
  {"institutionCode": "100027", "institutionName": "INTELLIFIN", "category": 10},
  {"institutionCode": "100028", "institutionName": "AG MORTGAGE BANK PLC", "category": 7},
  {"institutionCode": "100029", "institutionName": "INNOVECTIVES KESH", "category": 11},
  {"institutionCode": "100031", "institutionName": "FCMB EASY ACCOUNT", "category": 10},
  {"institutionCode": "100032", "institutionName": "CONTEC GLOBAL", "category": 10},
  {"institutionCode": "100033", "institutionName": "PALMPAY", "category": 10},
  {"institutionCode": "100034", "institutionName": "ZWallet", "category": 10},
  {"institutionCode": "100035", "institutionName": "M36", "category": 10},
  {"institutionCode": "100036", "institutionName": "KEGOW(CHAMSMOBILE)", "category": 10},
  {"institutionCode": "100039", "institutionName": "PAYSTACK-TITAN", "category": 10},
  {"institutionCode": "100040", "institutionName": "Xpresswallet", "category": 10},
  {"institutionCode": "100052", "institutionName": "BETA-ACCESS YELLO", "category": 10},
  {"institutionCode": "110001", "institutionName": "PAYATTITUDE ONLINE", "category": 11},
  {"institutionCode": "110002", "institutionName": "FLUTTERWAVE TECHNOLOGY SOLUTIONS LIMITED", "category": 11},
  {"institutionCode": "110003", "institutionName": "INTERSWITCH LIMITED", "category": 11},
  {"institutionCode": "110004", "institutionName": "First Apple Limited", "category": 11},
  {"institutionCode": "110005", "institutionName": "3LINE CARD MANAGEMENT LIMITED", "category": 11},
  {"institutionCode": "110006", "institutionName": "PAYSTACK PAYMENTS LIMITED", "category": 11},
  {"institutionCode": "110007", "institutionName": "TEAM APT", "category": 11},
  {"institutionCode": "110008", "institutionName": "KADICK INTEGRATION LIMITED", "category": 11},
  {"institutionCode": "110009", "institutionName": "Venture Garden Nigeria Limited", "category": 11},
  {"institutionCode": "110010", "institutionName": "Interswitch Financial Inclusion Services (IFIS)", "category": 9},
  {"institutionCode": "110011", "institutionName": "Arca Payments", "category": 11},
  {"institutionCode": "110012", "institutionName": "Cellulant PSSP", "category": 11},
  {"institutionCode": "110013", "institutionName": "QR Payments", "category": 11},
  {"institutionCode": "110014", "institutionName": "Cyberspace Limited", "category": 11},
  {"institutionCode": "110015", "institutionName": "Vas2nets Limited", "category": 11},
  {"institutionCode": "110017", "institutionName": "CROWDFORCE", "category": 11},
  {"institutionCode": "110018", "institutionName": "Microsystems Investment and Development Limited", "category": 11},
  {"institutionCode": "110019", "institutionName": "NIBSSUSSD PAYMENTS", "category": 11},
  {"institutionCode": "110021", "institutionName": "Bud infrastructure Limited", "category": 11},
  {"institutionCode": "110022", "institutionName": "Koraypay", "category": 11},
  {"institutionCode": "110023", "institutionName": "Capricorn Digital", "category": 11},
  {"institutionCode": "110024", "institutionName": "Resident Fintech Limited", "category": 10},
  {"institutionCode": "110025", "institutionName": "NetApps Technology Limited", "category": 11},
  {"institutionCode": "110026", "institutionName": "SPAY business", "category": 11},
  {"institutionCode": "110027", "institutionName": "Yello Digital financial services", "category": 11},
  {"institutionCode": "110028", "institutionName": "Nomba financial services Limited", "category": 11},
  {"institutionCode": "110029", "institutionName": "Woven Finance", "category": 11},
  {"institutionCode": "110044", "institutionName": "Leadremit Limited", "category": 11},
  {"institutionCode": "110075", "institutionName": "IROFIT TECHNOLOGIES LIMITED", "category": 11},
  {"institutionCode": "120001", "institutionName": "9 payment service Bank", "category": 12},
  {"institutionCode": "120002", "institutionName": "HopePSB", "category": 12},
  {"institutionCode": "120003", "institutionName": "MoMo PSB", "category": 12},
  {"institutionCode": "120004", "institutionName": "SmartCash Payment Service bank", "category": 12},
  {"institutionCode": "120005", "institutionName": "Money Master PSB", "category": 12},
  {"institutionCode": "400001", "institutionName": "FSDH", "category": 6},
  {"institutionCode": "999999", "institutionName": "NIP VIRTUAL BANK", "category": 11}
];

export async function GET() {
  try {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 5000);

    const response = await fetch(`${process.env.PAYMENT_BASE_URL}/partners/financial-institution`, {
      method: "GET",
      headers: {
        "x-api-key": process.env.PAYMENT_API_KEY!,
        "merchant-id": process.env.PAYMENT_MERCHANT_ID!,
      },
      signal: controller.signal 
    });

    clearTimeout(timeoutId); 

    const textResponse = await response.text();
    let data;
    
    try {
      data = JSON.parse(textResponse);
    } catch (e) {
      console.error("❌ Banks API Parse Error:", textResponse);
      throw new Error("Invalid response from provider"); 
    }

    if (response.ok && data.success) {
      const banks = data.data.sort((a: any, b: any) => 
        a.institutionName.localeCompare(b.institutionName)
      );
      return NextResponse.json({ success: true, banks });
    }

    throw new Error(data?.message || "Failed to fetch live banks"); 

  } catch (error: any) {
    console.warn("⚠️ Live Bank API delayed or failed. Serving local fallback. Reason:", error.message);
    
    const sortedLocalBanks = LOCAL_BANK_LIST.sort((a: any, b: any) => 
      a.institutionName.localeCompare(b.institutionName)
    );

    return NextResponse.json({ 
        success: true, 
        banks: sortedLocalBanks,
        fallbackUsed: true 
    });
  }
}